### ISSUE TITLE
Problems importing key in Android OpenVPN Connect app

### ISSUE THREAD

**Issue by gschaffner** [StarshipEngineer/OpenVPN-Setup#25] opened 2016-01-09 07:17 UTC
Using  [my (very slightly modified) fork of the repo](https://github.com/FISHunderscore/OpenVPN-Setup) to run the server and generate the keys, I get an error when importing the keys into the Android app.

> Error parsing OpenVPN profile: FISHunderscore1.ovpn : option_error: remote option not specified

My guess is that this is due to my modifications, which were intended to make the script work for the current version of Raspbian (on a Pi 2).

**Comment by d-budde** [comment] 2016-01-09 10:47
If you're getting this error then something is wrong with your public IP address.  Check the .opvn file and see if you specified the public ip correctly when you ran the script.  Are you using a ddns service?  If so, is that returning a correct IP address?  Try to ping it to see if it is working.

**Comment by FISHunderscore** [comment] 2016-01-09 20:09
I am using DuckDNS, and it's returning the correct IP when pinged. During the setup script, I set my public IP to FISHunderscore.duckdns.org (not my actual address for security, but the real one does work). Should I try to set up again with http://ganden.duckdns.org/ instead?

**Comment by FISHunderscore** [comment] 2016-01-09 20:37
Note: Changing my public IP to my actual public IP, not the DDNS address, and generating a new key (which is confirmed not the exact same) still results in:

> Error parsing OpenVPN profile: FISHunderscore1.ovpn : option_error: remote option not specified

**Comment by d-budde** [comment] 2016-01-09 21:22
Couple of comments:

1.  I was never able to get duckdns to work.  I spent several days trying but to no avail.  I switched to noip and it worked first time.  So I never looked back and tried to resolve that problem.

2.  If you recreate keys and use the same client name without first removing everything about the client in the /etc/openvpn/easy-rsa/keys directory, then some stuff is left out of the resulting client.ovpn file.  I never understood this either.  Just make sure the resulting client.ovpn file looks correct before importing it to your client machine.  Sometimes the default.txt information was missing (resulting in a remote error).  Other times, the certificate information (between <cert> and </cert> was missing which causes get a certificate error.

**Comment by FISHunderscore** [comment] 2016-01-09 21:34
1. I have DuckDNS working on my RPI (I can get into my router settings from an outside network through it).

2. Before recreating keys, I ran 
```
sudo ./remove.sh
```
Which does
```
rm -r /etc/openvpn /home/pi/ovpns
```
I recreated the keys with a fresh install of OpenVPN and easy-rsa, which the script did.

What should my FISHunderscore.ovpn file look like? Currently, it contains [this](http://pastebin.com/EMWw5zJs). I've censored out things that are potentially personal.

**Comment by d-budde** [comment] 2016-01-09 21:37
Looks like you are missing the default.txt information which should be at the beginning of the file.

**Comment by FISHunderscore** [comment] 2016-01-09 21:39
Could that be due to the repo being cloned into /home/pi/Desktop/ instead of /home/pi/?

Going to try it with the repo there.

**Comment by d-budde** [comment] 2016-01-09 21:40
you need to have a file called Default.txt in the Open-VPN-Setup directory from which you run the script.  It should look like this:

client
dev tun
proto udp
remote PUBLICIP 1194
resolv-retry infinite
nobind
persist-key
persist-tun
mute-replay-warnings
ns-cert-type server
key-direction 1
cipher AES-128-CBC
comp-lzo
verb 1
mute 20

**Comment by FISHunderscore** [comment] 2016-01-09 21:41
Also, interestingly, the comment in my .ovpn file says 2048 bit encryption, even when I choose 1024. Maybe related to [this](https://github.com/FISHunderscore/OpenVPN-Setup/commit/06cde3a8f79f80aa9a58dcdcffb8aa9e80b04d83)?

**Comment by d-budde** [comment] 2016-01-09 21:41
that 'remote PUBLICIP 1194' command gets translated in the script to your dns IP

**Comment by FISHunderscore** [comment] 2016-01-09 21:43
Yep, the new key has what it should at the top. Moving it onto my phone now for testing in OpenVPN Connect.

Thanks for you help!

**Comment by FISHunderscore** [comment] 2016-01-09 22:04
So now, I'm not getting the same error on my phone anymore, and I can input the password for the .ovpn key I generated. However, when I click connect, it looks up the DNS name, and gets stuck "waiting for server", eventually having a timeout.

The only other thing that I should have to do would be port forwarding 1194 UDP to my RPi, which I did. Everything else (firewall on RPi) should have been handled by the script, right?

**Comment by d-budde** [comment] 2016-01-09 23:30
As long as you follow the readme directions exactly then the script should do everything else that needs to be done.  I'd try without the ddns first and eliminate duckdns as the problem first.  If that still doesn't work then I'd go through it manually following the read/write tutorial and check every step.

**Closed** 2019-08-24 23:53 UTC
